apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwOC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYUdGMGRIbDRORFF4UUdkdFlXbHNMbU52YlRwTFlXeGhjRUF4TWpNME5RPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
